### ISSUE TITLE
Switching across multiple desktops

### ISSUE THREAD

**Issue by Perlence** [pmb6tz/windows-desktop-switcher#8] opened 2016-06-26 20:54 UTC
My setup has 4 virtual desktops, and I noticed that often times when switching from first to fourth desktop, some windows from second or third or even both appear flashing on fourth desktop. I guess that's because to get to it I have to cycle through each desktop in between.

I've managed to fix that[1] by choosing target desktop on Task View and only then switching to it. It goes like this:
- Press <kbd>Win</kbd> + <kbd>Tab</kbd> to open Task View
- Press <kbd>Tab</kbd> to focus desktops
- Press <kbd>Right</kbd> _n_ times, where _n_ is _target desktop number - 1_
- Press <kbd>Enter</kbd> to open selected desktop

On the downside you can see a bit of Task View opening animation, but the wait is unnoticeable.

If you encountered this problem before and you're OK with the solution, I'd be grateful to create a PR.

[1]https://github.com/Perlence/windows-desktop-switcher/commit/a8cb3e08eb7a6b19cb8dfe38fe366ce3cf551af9

**Comment by hawkins** [comment] 2016-06-28 22:55
> On the downside you can see a bit of Task View opening animation, but the wait is unnoticeable.

The wait is significantly longer for me if I'm only moving one desktop over to the right/left. Normally it'd be one quick animation, but instead we're paging through each virtual desktop from 1 to _n_ until we arrive at the target desktop.

What if we only iterated from 1 to _n_ when the target desktop is more than 1 or 2 away? That would further reduce the animation time for the small cases like I mentioned, yet still aim to avoid the flashing issue you originally mentioned.

**Comment by pmb6tz** [comment] 2016-06-29 01:51
Very much concur with @hawkins on that one. For me, I disable animation anyway so often I don't even really see the flashing being referenced, though I know it's a problem for most.

**Comment by Perlence** [comment] 2016-06-29 06:29
> I disable animation anyway so often I don't even really see the flashing being referenced

I'll try disabling animation and see if it helps, thanks! In fact I'll try different animation settings.

> What if we only iterated from 1 to n when the target desktop is more than 1 or 2 away?

Good idea, I'll try it as well.

**Comment by Perlence** [comment] 2016-06-29 10:48
So I checked out your master branch, disabled animations, and I noticed, that this flashing issue also applies to adjacent desktops, e.g. if I'm on second desktop and switch to first, some windows from second start flashing, namely Firefox, also DebugView. This doesn't happen if I just switch desktops with <kbd>Win</kbd> + <kbd>Ctrl</kbd> + <kbd>Arrow</kbd>.

**Comment by Perlence** [comment] 2016-06-30 22:20
> The wait is significantly longer for me if I'm only moving one desktop over to the right/left.

This can be adjusted by changing `SetKeyDelay`.

> I don't even really see the flashing being referenced

Maybe I wasn't clear once again. I did not mean "flashing", as in "they flash before my eyes" :smile:
I mean they actually _flash_, glow orange in task bar, like this:

https://yadi.sk/i/SHHg4TzQsvCh2
https://yadi.sk/i/fbJxm-w6svChw

**Comment by hawkins** [comment] 2016-09-27 20:14
So where'd we wind up on this one? Looks like I thought we needed a better solution for small moves.

Did you ever determine a cause or solution for the flashing issue? I'm not sure if I was ever able to reproduce that issue.

**Comment by Perlence** [comment] 2016-09-29 07:50
No, I didn't investigate this issue further to find the cause of flashing. I still use described method of switching on daily basis though. Sometimes pressing hotkey to jump to desktop by number does nothing, but pressing <kbd>Win</kbd> + <kbd>Tab</kbd> afterwards switches to desired desktop.

I will play with it in my free time.

**Comment by Perlence** [comment] 2016-09-29 11:26
If only I experience this problem, then pulling this solution into upsteam isn't rational. I tried different hotkeys to trigger switch. <kbd>Control</kbd> + <kbd>Number</kbd> kind of makes flashing less frequent then <kbd>Alt</kbd> + <kbd>Number</kbd>. This made me think that modifier key somehow is not blocked when changing desktops, but mapping Numpad digits also makes windows flash. Setting `SendMode, Input` also doesn't help.

**Comment by pmb6tz** [comment] 2016-09-29 17:17
I've actually hit this now and it happens more frequently than I'd like. I'll take a look at your solution and see how I fare. Thanks!

**Comment by Perlence** [comment] 2016-09-29 20:30
@pmb6tz Hey, good to see you back! How are you doing?

**Comment by pmb6tz** [comment] 2016-09-30 00:33
Hey @Perlence -- issues are still around but I couldn't stay away... :D. Hopefully getting there though!

**Comment by Perlence** [comment] 2016-09-30 09:58
The original flashing issue cannot be fixed by longer delay, e.g `SetKeyDelay, 200`.

**Comment by Perlence** [comment] 2016-10-06 07:35
> Sometimes pressing hotkey to jump to desktop by number does nothing

Although AHK does send `^#{Tab}`, the Task View does not open sometimes. I kind of fixed this by waiting for it to show up, and if it's not showing, try to open it again in a loop after some timeout.

**Comment by mzomparelli** [comment] 2017-05-02 23:45
I put a lot of work into this app to make it the best Windows 10 Virtual Desktop manager

https://github.com/mzomparelli/zVirtualDesktop

**Comment by mzomparelli** [comment] 2017-05-02 23:57
I'm curious why this project though. There are other AHK projects that utilize a DLL that utilizes the actual IVirtualDesktop COM interface. I disliked AHK for virtual desktop purposes. I just wanted an app that would do everything for me. There wasn't one so I created it. It uses the IVirtualDesktop COM interface which is why it feels natural and fluid like Microsoft had put it there.

**Comment by mzomparelli** [comment] 2017-05-09 04:13
I thought I would come back here to provide the solution to the flashing window. Did you figure it out yet?

**Comment by pmb6tz** [comment] 2017-05-09 04:19
@mzomparelli please stop advertising here--I'm happy to accept submissions for alternatives & put them in the Readme (this was a quick script I hacked together for my purposes, I never meant for it to be used this much) but I'd appreciate if you stop derailing these conversations.

**Comment by mzomparelli** [comment] 2017-05-09 04:24
Sorry, I'm not meaning to be that way. I just want to help you and show others a different solution. Someone here mentioned the flashing window, but I'll just keep that to myself then.

**Comment by Elijas** [comment] 2018-11-26 16:36
The flashing windows appeared to me too. I suspected that it's due to focus being put on the intermediary windows while switching desktops, this theory appears to be true, since it seems to have fixed it.

I've submitted a PR: https://github.com/pmb6tz/windows-desktop-switcher/pull/19

**Comment by pmb6tz** [comment] 2019-04-10 23:24
This issue should be fixed due to #19 , I'm going to go ahead and close this issue. Thanks!

**Closed as completed by pmb6tz** 2019-04-10 23:24 UTC
